Rework publish release action

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -13,27 +13,74 @@ env:
   DOCKER_BASE_IMAGE_DOCKERFILE: ./docker/Dockerfile-base
 
 jobs:
-  test:
-    name: Test
+  generate_info:
+    name: Generate info
     runs-on: ubuntu-latest
+    outputs:
+      docker-tags: ${{ steps.generate_docker_info.outputs.tags }}
+      pypi-version: ${{ steps.parse_version_tag.outputs.pypi_version }}
     steps:
-    - name: Check releases
-      run: |
-        latest_tag=$(
-          curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ github.token }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ github.repository }}/releases/latest \
-            | jq -r '.tag_name'
-        )
-        echo "Latest tag: $latest_tag"
-        exit 1
+      - name: Parse version tag
+        id: parse_version_tag
+        run: |
+          tag_name="${{ github.event.release.tag_name }}"
+
+          if [[ ! "${tag_name}" =~ ^v([0-9]{2})\.([0-9]{1,2})\.([0-9]+)$ ]]; then
+            echo "::error::Tag name must be in the format vYY.MM.MICRO"
+            exit 1
+          fi
+
+          year_output="year=${BASH_REMATCH[1]}"
+          month_output="month=${BASH_REMATCH[2]}"
+          pypi_output="pypi-version=${tag_name#v}"
+
+          echo "${year_output}"
+          echo "${month_output}"
+          echo "${pypi_output}"
+
+          echo "${year_output}" >> $GITHUB_OUTPUT
+          echo "${month_output}" >> $GITHUB_OUTPUT
+          echo "${pypi_output}" >> $GITHUB_OUTPUT
+
+      - name: Get latest release
+        id: get_latest_release
+        run: |
+          latest_tag=$(
+            curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ github.token }}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/${{ github.repository }}/releases/latest \
+              | jq -r '.tag_name'
+          )
+          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
+
+      - name: Generate Docker info
+        id: generate_docker_info
+        run: |
+          tag_year="${{ steps.parse_version_tag.outputs.year }}"
+          tag_month="${{ steps.parse_version_tag.outputs.month }}"
+          latest_tag="${{ steps.get_latest_release.outputs.latest_tag }}"
+
+          tags="${tag_year}.${tag_month}"
+
+          if [[ "${tag_month}" == "12" ]]; then
+            tags+=",LTS"
+          fi
+
+          if [[ "${latest_tag}" == "${{ github.event.release.tag_name }}" ]]; then
+            tags+=",latest"
+          fi
+
+          tags_output="tags=${tags}"
+
+          echo "${tags_output}"
+          echo "${tags_output}" >> $GITHUB_OUTPUT
 
   publish_package:
     name: Build and publish package
     runs-on: ubuntu-latest
-    needs: test
+    needs: generate_info
     steps:
     - name: Checkout repo
       uses: actions/checkout@v3
@@ -48,13 +95,7 @@ jobs:
 
     - name: Update package version
       run: |
-        tag_name="${{ github.event.release.tag_name }}"
-        if [[ $tag_name != v* ]]; then
-          echo "::error::Tag name must start with 'v'"
-          exit 1
-        fi
-        version="${tag_name#v}"  # Removes the leading 'v'
-        echo "__version__ = \"${version}\"" > sanic/__version__.py
+        echo "__version__ = \"${{ needs.generate_info.outputs.pypi-version }}\"" > sanic/__version__.py
 
     - name: Build a binary wheel and a source tarball
       run: python -m build --sdist --wheel --outdir dist/ .
@@ -68,7 +109,7 @@ jobs:
 
   publish_docker:
     name: Publish Docker / Python ${{ matrix.python-version }}
-    needs: publish_package
+    needs: [generate_info, publish_package]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
@@ -96,11 +137,27 @@ jobs:
           build-args: |
             PYTHON_VERSION=${{ matrix.python-version }}
 
+      - name: Parse tags for this Python version
+        id: parse_tags
+        run: |
+          IFS=',' read -ra tags <<< "${{ needs.generate_info.outputs.docker-tags }}"
+          tag_args=""
+
+          for tag in "${tags[@]}"; do
+              tag_args+=",${{ env.DOCKER_ORG_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.python-version }}-${tag}"
+          done
+
+          tag_args_output="tag_args=${tag_args:1}"
+
+          echo "${tag_args_output}"
+          echo "${tag_args_output}" >> $GITHUB_OUTPUT
+
       - name: Build and push Sanic image
         uses: docker/build-push-action@v4
         with:
           push: ${{ env.IS_TEST == 'false' }}
           file: ${{ env.DOCKER_IMAGE_DOCKERFILE }}
-          tags: ${{ env.DOCKER_ORG_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.python-version }}
+          tags: ${{ steps.parse_tags.outputs.tag_args }}
           build-args: |
             BASE_IMAGE_TAG=${{ matrix.python-version }}
+            SANIC_PYPI_VERSION=${{ needs.generate_info.outputs.pypi-version }}
